title: "Sam & Moore"
email: me@samandmoore.com
description: >
  Hi there! This is the personal website of yours truly, Sam Moore.
  I am a software engineer living and working in New York City. I
  spend my free time reading and contemplating how to be better at
  writing software and mentoring other engineers.
baseurl: ""
url: "http://samandmoore.com"
twitter_username: samandmoore
github_username:  samandmoore

markdown: kramdown

google_analytics_tracking_id: UA-22795654-1

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin

destination: _site

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: '/tags/:name/'
